# Generated by Django 4.2.6 on 2023-10-26 10:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('trans_date', models.DateField(default=datetime.date(2023, 10, 26))),
            ],
        ),
    ]
